alias sbf='stack build --fast'
alias rms='make run-mobility-stack'
alias beckn='cd /Users/juspay/nammayatri/Backend'
alias kernel='/Users/juspay/shared-kernel'
alias server-cold-start='sh /Users/juspay/.oh-my-zsh/custom/server-start.sh'
alias loadtest='cd /Users/juspay/nammayatri-loadtest'
alias make-driver='python3 script.py --operation make-driver -v'
